### ISSUE TITLE
Create working example of getting secret info out of GItHub secrets

### ISSUE THREAD

**Issue by galenatjpl** [unity-sds/unity-cs#22]

**Comment by galenatjpl** [comment]
Get a token, for example, from Github Secrets, for the purposes of testing/proving authentication.

**Comment by ramesh-maddegoda** [comment]
Created a working example as follows.

1) Created an EC2 instance.
2) Deployed a secured Java micro-service on the EC2 instance (this Java micro service is implemented to authenticate requests using an Amazon Cognito).
3) Generated a token.
4) Saved the token as a GitHub Encrypted secret.
5) Created a GitHub actions workflow.
6) Inside the  GitHub actions, passed the token as follows.
```
- shell: bash
        env:
          TEST_TOKEN: ${{ secrets.TEST_SECRET }}
        run: |
          curl -v -H "Authorization: Bearer $TEST_TOKEN" -s -N http://hostname:8081/api/hello
```
7) Executed the GitHub actions and observed the logs in Java micro-service.

The above test was successful and the micro-service was able to successfully authenticate the request that was made with the encrypted secret token .
